image: ubuntu:latest
#no free docker hmm
#image: devayansarkar/maven-node-openjdk

#todo npm install always fails
#client-build:
#  stage: build
#  only:
#      - master
#  script:
#    - cd client
#    - npm install
  # Keep node_modules-folder for the following stages:
#  artifacts:
#    paths:
#      - client/node_modules

#backend-build:
 # stage: build
  #only:
  #    - master
  #script:
   # - cd Backend
    #- "mvn install -B"

#backend-test:
 # stage: test
 # only:
 #     - master
 # script:
  #  - cd Backend
   # - mvn test
  #needs: ["backend-build"]


deploy:
  script:
    - mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - touch ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa # Required permission by ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - apt-get update
    - apt-get install --assume-yes rsync
    - rsync --archive --delete --exclude='.git' --exclude='target' Backend/ app@13.51.169.174:app
    - ssh app@13.51.169.174 systemctl --user restart app
  only:
    - backend-dev
