image: adoptopenjdk/maven-openjdk11

backend-build:
  stage: build
  only:
      - backend-dev
  script:
    - cd Backend
    - "mvn compile"
    - cp $application src/main/resources/application.properties

backend-test:
  stage: test
  only:
      - backend-dev
  script:
    - cd Backend
    - mvn test
  needs: ["backend-build"]

deploy:
  stage: deploy
  script:
    - apt-get update -y && apt-get install openssh-client -y
    - mkdir ~/.ssh
    - ssh-keyscan 13.51.58.86 > ~/.ssh/known_hosts
    - touch ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa # Required permission by ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - ssh app@13.51.58.86 ./runjava.sh
  only:
    - backend-dev
  needs: ["backend-build"]
