spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 812128741361-er3ul9d19er539e7n22ahnv81tfiq4sk.apps.googleusercontent.com
            clientSecret: pqtTESXJJa1SWiBzRV2vXfhg
            scope:
              - email
              - profile
          #TODO ADD MORE SOCIAL LOGIN OPTIONS